services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - network
    depends_on:
      - db

  web:
    image: nginx:alpine
    platform: linux/amd64 
    container_name: nginx
    volumes:
      - .:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${APP_PORT_EXPOSED:-8000}:80"
    networks:
      - network
    depends_on:
      - app

  db:
    image: mysql:5.7
    platform: linux/amd64 
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "${DB_DATABASE:-laravel_db}"
      MYSQL_USER: "${DB_USERNAME:-laravel_user}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-laravel_password}"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${DB_PORT_EXPOSED:-3306}:3306"
    networks:
      - network

volumes:
  db_data:

networks:
  network:
